package generazioneAvvisi.spcoop.nodopagamentispc.servizi.richiestaavvisi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.3 2021-06-03T16:09:30.437+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/RichiestaAvvisi", name = "GenerazioneAvvisi")
@XmlSeeAlso({ generazioneAvvisi.ws.ppthead.ObjectFactory.class, generazioneAvvisi.ws.ObjectFactory.class,
		merged.digitpa.schemas._2011.pagamenti.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GenerazioneAvvisi {

	@WebMethod(action = "paaChiediNumeroAvviso")
	@Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaChiediNumeroAvvisoRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaChiediNumeroAvvisoRisposta")
	@WebResult(name = "paaChiediNumeroAvvisoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
	public generazioneAvvisi.ws.PaaChiediNumeroAvvisoRisposta paaChiediNumeroAvviso(

			@WebParam(partName = "bodyrichiesta", name = "paaChiediNumeroAvviso", targetNamespace = "http://ws.pagamenti.telematici.gov/") generazioneAvvisi.ws.PaaChiediNumeroAvviso bodyrichiesta,
			@WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true) generazioneAvvisi.ws.ppthead.IntestazionePPT header);
}
