package merged.pagopa.pagopa_api.pa.pafornode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2022-12-01T11:03:15.780+01:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://pagopa-api.pagopa.gov.it/paForNode", name = "paForNode")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaForNode {

    @WebMethod(action = "paaAttivaRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaAttivaRPTRisposta")
    @WebResult(name = "paaAttivaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public PaaAttivaRPTRisposta paaAttivaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaAttivaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        PaaAttivaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        IntestazionePPT header
    );

    @WebMethod(action = "paGetPayment")
    @WebResult(name = "paGetPaymentRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaGetPaymentRes paGetPayment(
        @WebParam(partName = "bodyrequest", name = "paGetPaymentReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaGetPaymentReq bodyrequest
    );

    @WebMethod(action = "paSendRT")
    @WebResult(name = "paSendRTRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaSendRTRes paSendRT(
        @WebParam(partName = "bodyrequest", name = "paSendRTReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaSendRTReq bodyrequest
    );

    @WebMethod(action = "paGetPaymentV2")
    @WebResult(name = "paGetPaymentV2Response", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaGetPaymentV2Response paGetPaymentV2(
        @WebParam(partName = "bodyrequest", name = "paGetPaymentV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaGetPaymentV2Request bodyrequest
    );

    @WebMethod(action = "paDemandPaymentNotice")
    @WebResult(name = "paDemandPaymentNoticeResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaDemandPaymentNoticeResponse paDemandPaymentNotice(
        @WebParam(partName = "bodyrequest", name = "paDemandPaymentNoticeRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaDemandPaymentNoticeRequest bodyrequest
    );

    @WebMethod(action = "paaVerificaRPT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaVerificaRPTRisposta")
    @WebResult(name = "paaVerificaRPTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public PaaVerificaRPTRisposta paaVerificaRPT(
        @WebParam(partName = "bodyrichiesta", name = "paaVerificaRPT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        PaaVerificaRPT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        IntestazionePPT header
    );

    @WebMethod(action = "paVerifyPaymentNotice")
    @WebResult(name = "paVerifyPaymentNoticeRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaVerifyPaymentNoticeRes paVerifyPaymentNotice(
        @WebParam(partName = "bodyrequest", name = "paVerifyPaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaVerifyPaymentNoticeReq bodyrequest
    );

    @WebMethod(action = "paSendRTV2")
    @WebResult(name = "paSendRTV2Response", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "bodyresponse")
    public PaSendRTV2Response paSendRTV2(
        @WebParam(partName = "bodyrequest", name = "paSendRTV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaSendRTV2Request bodyrequest
    );
}
