package nodo.it.gov.spcoop.nodopagamentispc.servizi.pagamentitelematicirpt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-07T15:06:54.762+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "PagamentiTelematiciRPTservice",
                  wsdlLocation = "file:/D:/My%20Doc/Workspace/Test/PA.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT")
public class PagamentiTelematiciRPTservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTservice");
    public final static QName PagamentiTelematiciRPTPort = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRPT", "PagamentiTelematiciRPTPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/My%20Doc/Workspace/Test/PA.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciRPTservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/My%20Doc/Workspace/Test/PA.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciRPTservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PagamentiTelematiciRPTservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PagamentiTelematiciRPTservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort() {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciRPT
     */
    @WebEndpoint(name = "PagamentiTelematiciRPTPort")
    public PagamentiTelematiciRPT getPagamentiTelematiciRPTPort(WebServiceFeature... features) {
        return super.getPort(PagamentiTelematiciRPTPort, PagamentiTelematiciRPT.class, features);
    }

}
