package eu.sia.nodopa.merged.paaNodoNM4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-07-01T14:54:22.207+02:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/RichiestaAvvisi", name = "GenerazioneAvvisiMerged")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GenerazioneAvvisiMerged {

    @WebMethod(action = "paaChiediNumeroAvviso")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaChiediNumeroAvvisoRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaChiediNumeroAvvisoRisposta")
    @WebResult(name = "paaChiediNumeroAvvisoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public PaaChiediNumeroAvvisoRisposta paaChiediNumeroAvviso(

        @WebParam(partName = "bodyrichiesta", name = "paaChiediNumeroAvviso", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        PaaChiediNumeroAvviso bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        IntestazionePPT header
    );

    @WebMethod(action = "paDemandPaymentNotice")
    @WebResult(name = "paDemandPaymentNoticeResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd", partName = "responseBody")
    public PaDemandPaymentNoticeResponse paDemandPaymentNotice(

        @WebParam(partName = "requestBody", name = "paDemandPaymentNoticeRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd")
        PaDemandPaymentNoticeRequest requestBody
    );
}
