package eu.sia.nodopa.merged.paaNodoNM4;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-07-01T14:54:22.242+02:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "GenerazioneAvvisiservice",
                  wsdlLocation = "file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodoRichiestaAvvisiMerged.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/RichiestaAvvisi")
public class GenerazioneAvvisiservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/RichiestaAvvisi", "GenerazioneAvvisiservice");
    public final static QName PPTPortMerged = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/RichiestaAvvisi", "PPTPortMerged");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodoRichiestaAvvisiMerged.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GenerazioneAvvisiservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodoRichiestaAvvisiMerged.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GenerazioneAvvisiservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenerazioneAvvisiservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerazioneAvvisiservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GenerazioneAvvisiservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GenerazioneAvvisiservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GenerazioneAvvisiservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GenerazioneAvvisiMerged
     */
    @WebEndpoint(name = "PPTPortMerged")
    public GenerazioneAvvisiMerged getPPTPortMerged() {
        return super.getPort(PPTPortMerged, GenerazioneAvvisiMerged.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerazioneAvvisiMerged
     */
    @WebEndpoint(name = "PPTPortMerged")
    public GenerazioneAvvisiMerged getPPTPortMerged(WebServiceFeature... features) {
        return super.getPort(PPTPortMerged, GenerazioneAvvisiMerged.class, features);
    }

}
