apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mock-ec-prf

images:
  - name: mock-ec-prf-image
    #newName: nodopauatregistrypci.azurecr.io/mock-ec-prf
    #newTag: 1.1.1

resources:
  - namespace.yaml
  - ingress.yaml
  - ../base

generatorOptions:
  disableNameSuffixHash: true
  
patches:
  - path: deployment.yaml