pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: prf
    values:
      - prf

variables:
  repository: 'mock-ec-prf'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  kustomizeFolderApp: '$(Build.SourcesDirectory)/kustomize'

stages:
  - stage: retrieve_info
    displayName: "Retrieve info (${{ parameters.env }})"
    jobs:
      - job: retrieve_info
        displayName: "Retrieve info (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          - task: Bash@3
            displayName: Get POM version
            name: getVar
            inputs:
              targetType: 'inline'
              script: |
                APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                echo $APP_VERSION
                echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$APP_VERSION"
              failOnStderr: true

  - stage: build
    displayName: "Build (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
    variables:
      - group: nodo-mock-perf
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: build
        displayName: "Build (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          - task: Docker@2
            displayName: 'Build and push image'
            inputs:
              containerRegistry: $(container-registry-service-connection-${{ parameters.env }})
              repository: $(repository)
              command: 'buildAndPush'
              Dockerfile: $(dockerfile)
              tags: $(appVersion)

  - stage: push_manifest
    displayName: "Push manifest (${{ parameters.env }})"
    condition: succeeded()
    dependsOn:
      - retrieve_info
      - build
    variables:
      - group: nodo-mock-perf
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    jobs:
      - job: push_manifest
        displayName: "Push manifest ${{ parameters.env }}"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true

          - task: KubernetesManifest@0
            name: "bakeApp"
            inputs:
              action: "bake"
              renderType: 'kustomize'
              kustomizationPath: $(kustomizeFolderApp)/${{ parameters.env }}
              containers: $(repository-docker-${{ parameters.env }})/$(repository):$(appVersion)
            displayName: "Create manifest app (${{ parameters.env }})"

          - publish: $(bakeApp.manifestsBundle)
            displayName: "Publish manifest app (${{ parameters.env }})"
            artifact: $(appVersion)-${{ parameters.env }}-manifest-app

  - stage: deploy
    displayName: "Deploy (${{ parameters.env }})"
    dependsOn:
      - retrieve_info
      - build
      - push_manifest
    variables:
      - group: nodo-mock-perf
      - name: appVersion
        value: $[ stageDependencies.retrieve_info.retrieve_info.outputs['getVar.APP_VERSION'] ]
    condition: succeeded()
    jobs:
      - job: deploy
        displayName: "Deploy ${{ parameters.env }}"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none

          - script: |
              ls -la $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-manifest-app
              rm -rf $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-manifest-app
            displayName: "Clean old cached files $(appVersion)-${{ parameters.env }}-manifest-app"

          - download: current
            artifact: $(appVersion)-${{ parameters.env }}-manifest-app
            displayName: "Download manifest app $(appVersion)-${{ parameters.env }}-manifest-app"

          - task: KubernetesManifest@0
            displayName: "Deploy manifest for app"
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: u87-aks-pci-uat-self-connection-nodo
              namespace: mock-ec-prf
              manifests: $(Pipeline.Workspace)/$(appVersion)-${{ parameters.env }}-manifest-app/*.yaml