apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mock-ec-prf

images:
  - name: mock-ec-prf-image
    newName: toolbox.sia.eu/docker-pagopa/mock-ec-prf
    newTag: 1.1.1

resources:
  - route.yaml
  - ../base

generatorOptions:
  disableNameSuffixHash: true