package rt.spcoop.nodopagamentispc.servizi.pagamentitelematicirt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-06-21T14:52:23.602+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", name = "PagamentiTelematiciRT")
@XmlSeeAlso({rt.gov.telematici.pagamenti.ws.ppthead.ObjectFactory.class, rt.gov.telematici.pagamenti.ws.ObjectFactory.class})
public interface PagamentiTelematiciRT {

    @WebMethod(action = "paaInviaRichiestaRevoca")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRichiestaRevocaRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRichiestaRevocaRisposta")
    @RequestWrapper(localName = "paaInviaRichiestaRevoca", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "rt.gov.telematici.pagamenti.ws.PaaInviaRichiestaRevoca")
    @ResponseWrapper(localName = "paaInviaRichiestaRevocaRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "rt.gov.telematici.pagamenti.ws.PaaInviaRichiestaRevocaRisposta")
    @WebResult(name = "paaInviaRichiestaRevocaRisposta", targetNamespace = "")
    public rt.gov.telematici.pagamenti.ws.TipoInviaRichiestaRevocaRisposta paaInviaRichiestaRevoca(

        @WebParam(name = "identificativoDominio", targetNamespace = "")
        java.lang.String identificativoDominio,
        @WebParam(name = "identificativoUnivocoVersamento", targetNamespace = "")
        java.lang.String identificativoUnivocoVersamento,
        @WebParam(name = "codiceContestoPagamento", targetNamespace = "")
        java.lang.String codiceContestoPagamento,
        @WebParam(name = "rr", targetNamespace = "")
        byte[] rr
    );

    @WebMethod(action = "paaInviaRT")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaRTRisposta")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "paaInviaRTRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", partName = "bodyrisposta")
    public rt.gov.telematici.pagamenti.ws.PaaInviaRTRisposta paaInviaRT(

        @WebParam(partName = "bodyrichiesta", name = "paaInviaRT", targetNamespace = "http://ws.pagamenti.telematici.gov/")
        rt.gov.telematici.pagamenti.ws.PaaInviaRT bodyrichiesta,
        @WebParam(partName = "header", name = "intestazionePPT", targetNamespace = "http://ws.pagamenti.telematici.gov/ppthead", header = true)
        rt.gov.telematici.pagamenti.ws.ppthead.IntestazionePPT header
    );

    @WebMethod(action = "paaInviaEsitoStorno")
    @Action(input = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRichiesta", output = "http://ws.pagamenti.telematici.gov/PPT/paaInviaEsitoStornoRisposta")
    @RequestWrapper(localName = "paaInviaEsitoStorno", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "rt.gov.telematici.pagamenti.ws.PaaInviaEsitoStorno")
    @ResponseWrapper(localName = "paaInviaEsitoStornoRisposta", targetNamespace = "http://ws.pagamenti.telematici.gov/", className = "rt.gov.telematici.pagamenti.ws.PaaInviaEsitoStornoRisposta")
    @WebResult(name = "paaInviaEsitoStornoRisposta", targetNamespace = "")
    public rt.gov.telematici.pagamenti.ws.TipoInviaEsitoStornoRisposta paaInviaEsitoStorno(

        @WebParam(name = "identificativoIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoIntermediarioPA,
        @WebParam(name = "identificativoStazioneIntermediarioPA", targetNamespace = "")
        java.lang.String identificativoStazioneIntermediarioPA,
        @WebParam(name = "identificativoDominio", targetNamespace = "")
        java.lang.String identificativoDominio,
        @WebParam(name = "identificativoUnivocoVersamento", targetNamespace = "")
        java.lang.String identificativoUnivocoVersamento,
        @WebParam(name = "codiceContestoPagamento", targetNamespace = "")
        java.lang.String codiceContestoPagamento,
        @WebParam(name = "er", targetNamespace = "")
        byte[] er
    );
}
