package rt.spcoop.nodopagamentispc.servizi.pagamentitelematicirt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-06-21T14:52:23.638+02:00
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "PagamentiTelematiciRTservice",
                  wsdlLocation = "file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodo.wsdl",
                  targetNamespace = "http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT")
public class PagamentiTelematiciRTservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", "PagamentiTelematiciRTservice");
    public final static QName PPTPort = new QName("http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT", "PPTPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PagamentiTelematiciRTservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Sviluppo/Git/pagopa---testsuite/PA_Mock/src/main/resources/PaPerNodo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciRTservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PagamentiTelematiciRTservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PagamentiTelematiciRTservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PagamentiTelematiciRT
     */
    @WebEndpoint(name = "PPTPort")
    public PagamentiTelematiciRT getPPTPort() {
        return super.getPort(PPTPort, PagamentiTelematiciRT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciRT
     */
    @WebEndpoint(name = "PPTPort")
    public PagamentiTelematiciRT getPPTPort(WebServiceFeature... features) {
        return super.getPort(PPTPort, PagamentiTelematiciRT.class, features);
    }

}
